# https://taskfile.dev

version: '3'
includes:
  mlflow-gcs-llamacpp: scripts/tasks/mlflow_gcs_llamacapp/Taskfile.yml
  dev: scripts/dev/Taskfile.yml

dotenv: [.env]

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
