version: "3"
vars:
  CONTAINER_NAME: "lmorbits-embedding"
  IMAGE_NAME: "{{.CONTAINER_NAME}}-image"

tasks:
  serve:
    desc: "Start the embedding server"
    vars:
      MODEL_PATH: "{{.MODEL_PATH}}"
      MODEL_NAME: "{{.MODEL_NAME}}"
      PORT: "{{.PORT | default 1111}}"
    dir: "{{.MODEL_PATH}}"
    cmds:
      - |
        if [ "$(docker ps -q --filter "status=running" -f name={{.CONTAINER_NAME}}-{{.MODEL_NAME}})" ]; then
          echo "{{.CONTAINER_NAME}}-{{.MODEL_NAME}} is already running"
        elif [ "$(docker ps -q --filter "status=exited" -f name={{.CONTAINER_NAME}}-{{.MODEL_NAME}})" ]; then
          echo "Starting {{.CONTAINER_NAME}}-{{.MODEL_NAME}}"
          docker start {{.CONTAINER_NAME}}-{{.MODEL_NAME}}
        else
          echo "Building {{.IMAGE_NAME}} image"
          docker build -t {{.IMAGE_NAME}} -f Dockerfile .
          docker run -d -p {{.PORT}}:1111 --name {{.CONTAINER_NAME}}-{{.MODEL_NAME}} {{.IMAGE_NAME}}
        fi
        # health check on /health endpoint
        until curl -s http://localhost:{{.PORT}}/health | grep -q "ok"; do
          echo "Waiting for {{.CONTAINER_NAME}}-{{.MODEL_NAME}} to be ready..."
          sleep 1
        done
    silent: false

  stop:
    desc: "Stop the embedding server"
    vars:
      MODEL_NAME: "{{.MODEL_NAME}}"
    cmds:
      - |
        if [ "$(docker ps -q --filter "status=exited" -f name={{.CONTAINER_NAME}}-{{.MODEL_NAME}})" ]; then
          docker stop {{.CONTAINER_NAME}}-{{.MODEL_NAME}}
        fi
    silent: false
  delete:
    desc: "Delete the embedding server"
    vars:
      MODEL_NAME: "{{.MODEL_NAME}}"
    cmds:
      - |
        if [ "$(docker ps -q -f name={{.CONTAINER_NAME}}-{{.MODEL_NAME}})" ]; then 
          if [ "$(docker ps -q --filter "status=running" -f name={{.CONTAINER_NAME}}-{{.MODEL_NAME}})" ]; then
            echo "Stopping {{.CONTAINER_NAME}}-{{.MODEL_NAME}}"
            docker stop {{.CONTAINER_NAME}}-{{.MODEL_NAME}}
          fi
          echo "Removing {{.CONTAINER_NAME}}-{{.MODEL_NAME}}"
          docker rm {{.CONTAINER_NAME}}-{{.MODEL_NAME}}
        else
          echo "{{.CONTAINER_NAME}}-{{.MODEL_NAME}} is not running"
        fi
    silent: false
